# Generated by Django 5.2.17 on 2026-09-13 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_chaintip_authorprofile_paymentorder_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='amount_sats',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='provider',
            field=models.CharField(default='btcpay', max_length=12),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='quote_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='txid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='DraftChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveIntegerField(default=1)),
                ('markdown', models.TextField(blank=True, max_length=500000)),
                ('version', models.PositiveIntegerField(default=0)),
                ('art', models.BinaryField(blank=True, default=bytes)),
                ('art_type', models.CharField(blank=True, max_length=30)),
                ('art_alt', models.CharField(blank=True, max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_chapters', to='studio.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='studio.paymentorder')),
            ],
        ),
        migrations.CreateModel(
            name='StoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('character', 'Character'), ('location', 'Location'), ('rule', 'World rule'), ('continuity', 'Continuity fact'), ('task', 'Revision task')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField(blank=True, max_length=12000)),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_entries', to='studio.project')),
            ],
        ),
        migrations.CreateModel(
            name='StoryWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=dict)),
                ('roster', models.JSONField(default=dict)),
                ('clues', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_workspace', to='studio.project')),
            ],
        ),
        migrations.CreateModel(
            name='ClueAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(max_length=120)),
                ('passage_id', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, max_length=4000)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clue_annotations', to='studio.revision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('revision', 'clue', 'passage_id'), name='unique_revision_clue_passage')],
            },
        ),
        migrations.CreateModel(
            name='SemanticReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_id', models.CharField(max_length=16)),
                ('result', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=100)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_readings', to='studio.revision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('revision', 'passage_id'), name='unique_semantic_passage')],
            },
        ),
    ]
