# Generated by Django 5.2.17 on 2026-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_paymentorder_address_paymentorder_amount_sats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='channel',
            field=models.CharField(choices=[('general', 'General'), ('poetry', 'Poetry'), ('fiction', 'Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('erotica', 'Erotica'), ('non-fiction', 'Non-Fiction'), ('memoir', 'Memoir'), ('fantasy', 'Fantasy'), ('science-fiction', 'Science Fiction'), ('horror', 'Horror'), ('historical-fiction', 'Historical Fiction'), ('essays', 'Essays')], db_index=True, default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='publications', to='studio.tag'),
        ),
    ]
