# Generated by Django 5.2.17 on 2026-09-14 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='Allow new ordinal editions and wallet mint requests. Existing inscriptions remain readable.')),
                ('special_sats_enabled', models.BooleanField(default=False, help_text='Allow export to Gamma for special-sat inscriptions.')),
            ],
        ),
        migrations.CreateModel(
            name='OrdinalEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('sat_mode', models.CharField(choices=[('regular', 'Regular sat'), ('special', 'Special sat')], max_length=12)),
                ('requested_sat', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prepared', 'Ready'), ('awaiting', 'Awaiting inscription'), ('submitted', 'Verifying'), ('minted', 'Minted')], default='prepared', max_length=12)),
                ('inscription_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('txid', models.CharField(blank=True, max_length=64)),
                ('sat_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sat_rarity', models.CharField(blank=True, max_length=20)),
                ('marketplace_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordinal', to='studio.publication')),
            ],
        ),
    ]
