# Generated by Django 5.2.17 on 2026-09-14 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_walletchallenge_walletidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinalHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100)),
                ('outpoint', models.CharField(max_length=80)),
                ('checked_at', models.DateTimeField()),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='studio.ordinaledition')),
            ],
        ),
        migrations.CreateModel(
            name='OrdinalListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_address', models.CharField(max_length=100)),
                ('payout_address', models.CharField(max_length=100)),
                ('price_sats', models.PositiveBigIntegerField()),
                ('outpoint', models.CharField(max_length=80)),
                ('postage_sats', models.PositiveBigIntegerField()),
                ('unsigned_psbt', models.TextField()),
                ('signed_psbt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Awaiting signature'), ('active', 'For sale'), ('cancelled', 'Delisted'), ('sold', 'Sold'), ('stale', 'Ownership changed')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='studio.ordinaledition')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinalTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receive_address', models.CharField(max_length=100)),
                ('payment_address', models.CharField(max_length=100)),
                ('unsigned_psbt', models.TextField()),
                ('raw_transaction', models.TextField(blank=True)),
                ('txid', models.CharField(blank=True, max_length=64)),
                ('fee_sats', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('prepared', 'Review in wallet'), ('broadcasting', 'Broadcast pending'), ('broadcast', 'Awaiting confirmations'), ('confirmed', 'Collected'), ('conflict', 'Inputs spent elsewhere')], default='prepared', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='studio.ordinallisting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordinallisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'active'])), fields=('edition',), name='one_open_ordinal_listing'),
        ),
    ]
