# Generated by Django 5.2.17 on 2026-09-14 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_ordinalholding_ordinallisting_ordinaltrade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplimentaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('code_hint', models.CharField(editable=False, max_length=12)),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('three_months', 'Free three months'), ('lifetime', 'Lifetime access')], max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0, editable=False)),
                ('enabled', models.BooleanField(default=True)),
                ('redeem_before', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('issue_invitations', 'Can issue invitations')],
            },
        ),
        migrations.CreateModel(
            name='InviteRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('granted_until', models.DateTimeField(blank=True, null=True)),
                ('lifetime', models.BooleanField(default=False)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='studio.invitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('member_issuers_enabled', models.BooleanField(default=False, help_text='Allow people with the Can issue invitations permission to create codes. Admins always can.')),
            ],
            options={
                'verbose_name_plural': 'Invite settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='invite_settings_singleton')],
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__gte', 1)), name='invite_positive_uses'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('uses__lte', models.F('max_uses'))), name='invite_capacity'),
        ),
        migrations.AddConstraint(
            model_name='inviteredemption',
            constraint=models.UniqueConstraint(fields=('invitation', 'user'), name='invite_once_per_user'),
        ),
    ]
