# Generated by Django 5.2.17 on 2026-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_paymentorder_billing_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='profile',
            field=models.CharField(choices=[('general', 'General fiction'), ('river', 'The River Beyond Zero'), ('creepypasta', 'Creepypasta · darkness')], max_length=20),
        ),
    ]
