from django.urls import path
from .voting import vote
from . import ordinal_views, achievement_views
from . import views, community, story_views, bitcoin_views
urlpatterns = [
    path('publish/ordinal/',ordinal_views.ordinal_publish,name='ordinal-publish'),
    path('account/achievements/',achievement_views.achievements,name='achievements'),
    path('read/<uuid:publication_id>/ordinal/',ordinal_views.ordinal,name='ordinal'),
    path('read/<uuid:publication_id>/ordinal/wallet/',ordinal_views.ordinal_wallet,name='ordinal-wallet'),
    path('read/<uuid:publication_id>/ordinal/download/',ordinal_views.ordinal_download,name='ordinal-download'),
    path('read/<uuid:publication_id>/vote/',vote,name='vote'),
    path('account/wallet/',bitcoin_views.wallet,name='wallet'),
    path('read/<uuid:publication_id>/organize/',community.categorize,name='categorize'),
    path('chapters/<uuid:chapter_id>/notes/',story_views.chapter_note,name='chapter-note'),
    path('revisions/<uuid:revision_id>/to-chapters/',story_views.revision_to_chapters,name='revision-to-chapters'),
    path('account/bitcoin/start/',bitcoin_views.start,name='bitcoin-start'),
    path('account/bitcoin/<uuid:order_id>/',bitcoin_views.order_view,name='bitcoin-order'),
    path('account/storage/', story_views.storage, name='storage'),
    path('account/storage/<str:kind>/<uuid:item_id>/remove/', story_views.remove_content, name='remove-content'),
    path('projects/<uuid:project_id>/story/', story_views.story, name='story'),
    path('projects/<uuid:project_id>/board/', story_views.board, name='story-board'),
    path('story/entries/<uuid:entry_id>/', story_views.entry_action, name='entry-action'),
    path('projects/<uuid:project_id>/chapters/', story_views.chapters, name='chapters'),
    path('projects/<uuid:project_id>/chapters/<uuid:chapter_id>/', story_views.chapters, name='chapter-edit'),
    path('chapters/<uuid:chapter_id>/art/', story_views.art, name='chapter-art'),
    path('projects/<uuid:project_id>/snapshot/', story_views.chapter_snapshot, name='chapter-snapshot'),
    path('projects/<uuid:project_id>/edition/', story_views.edition, name='edition'),
    path('projects/<uuid:project_id>/story/export/', story_views.export_project, name='export-project'),
    path('revisions/<uuid:revision_id>/aids/', story_views.aids, name='story-aids'),
    path('revisions/<uuid:revision_id>/timeline.csv', story_views.timeline_csv, name='timeline-csv'),
    path('', community.feed, name='feed'),
    path('studio/', views.library, name='library'),
    path('join/', community.signup, name='signup'),
    path('account/', community.account, name='account'),
    path('account/membership/', community.membership, name='membership'),
    path('account/membership/status/', community.membership_status, name='membership-status'),
    path('account/membership/checkout/', community.checkout, name='checkout'),
    path('account/orders/<uuid:order_id>/check/', community.check_payment, name='check-payment'),
    path('publishing/locked/', community.lockout, name='lockout'),
    path('publish/', community.publish, name='publish'),
    path('authors/<uuid:author_id>/', community.author, name='author'),
    path('authors/<uuid:author_id>/follow/', community.follow, name='follow'),
    path('read/<uuid:publication_id>/', community.read, name='read'),
    path('read/<uuid:publication_id>/bookmark/', community.bookmark, name='bookmark'),
    path('read/<uuid:publication_id>/report/', community.report, name='report'),
    path('read/<uuid:publication_id>/withdraw/', community.withdraw, name='withdraw'),
    path('projects/<uuid:project_id>/', views.project, name='project'),
    path('revisions/<uuid:revision_id>/', views.revision, name='revision'),
    path('revisions/<uuid:revision_id>/notes/', views.add_note, name='add-note'),
    path('revisions/<uuid:revision_id>/export/', views.export_revision, name='export-revision'),
]
